trigger:
  batch: true
  paths:
    include:
      - app/client-app/*

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/yarn-cached.yml
  - template: templates/js-package.build.yml
    parameters:
      packageName: "@decsys/client-app"
