trigger:
  batch: true
  branches:
    exclude:
      - main # we don't need to build in isolation on merges to main
  paths:
    include:
      - app/client-app/*

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  # stop CRA's webpack build generating sourcemaps in production
  # this shouldn't affect the response item rollup builds
  # but tbh it doesn't matter if it does since this is for production
  GENERATE_SOURCEMAP: false

steps:
  - template: templates/yarn-cached.yml
  - template: templates/js-package.build.yml
    parameters:
      packageName: "client-app"
