trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

stages:
  # We do a restore up front
  # to ensure the rest of the jobs
  # get to use a populated cache
  - stage: Restore
    jobs:
      - job: Yarn
        steps:
          - template: templates/yarn-cached.yml

  # Build and publish artifacts of all the independent bits
  # that then get used in the Decsys app itself.
  - stage: Publish_Parts
    displayName: Publish Parts
    jobs:
      # read metadata and set derived variables
      # for the rest of the pipeline to use
      - job: Metadata
        steps:
          - task: LoadJsonVariables@1
            inputs:
              JsonSource: app/client-app/package.json
              VariablePrefix: pkg
            displayName: Read package.json
          - script: >-
              echo '##vso[task.setvariable
              variable=clientVersion;isOutput=true]$(pkg_version)'
            displayName: Set Variables

      # Generate a version metadata file for the platform
      - job: Version_File
        displayName: Create Version.txt
        dependsOn: Metadata
        variables:
          clientVersion: >-
            $[ dependencies.Metadata.outputs['clientVersion'] ]
        steps:
          - task: file-creator@5
            inputs:
              fileoverwrite: true
              skipempty: true
              filepath: $(Build.ArtifactStagingDirectory)/version.txt
              filecontent: |-
                Build=$(Build.BuildNumber)
                Client App=$(clientVersion)
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: version
