trigger:
  batch: true
  branches:
    exclude:
      - master # we don't need to build in isolation on merges to master
  paths:
    include:
      - app/Decsys/*

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: release
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "5.0.x"
      includePreviewVersions: true

  - script: >
      dotnet restore
      --locked-mode
    workingDirectory: app/Decsys
    displayName: dotnet restore
  - script: >
      dotnet build
      -c $(buildConfiguration)
      --no-restore
    workingDirectory: app/Decsys
    displayName: dotnet build
