trigger:
  batch: true
  paths:
    include:
      - app/Decsys/*

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: release
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
  - task: Cache@2
    inputs:
      key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**'
      restoreKeys: |
        nuget | "$(Agent.OS)"
      path: $(NUGET_PACKAGES)
    displayName: Cache NuGet packages

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
      includePreviewVersions: true

  - script: >
      dotnet restore
      --locked-mode
    workingDirectory: app/Decsys
    displayName: dotnet restore
  - script: >
      dotnet build
      -c $(buildConfiguration)
      --no-restore
    workingDirectory: app/Decsys
    displayName: dotnet build