trigger:
  batch: true
  paths:
    include:
      - app/Decsys/*

pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: release
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'
      includePreviewVersions: true
  - script: dotnet build -c $(buildConfiguration)
    workingDirectory: app/Decsys
    displayName: dotnet build