trigger:
  batch: true
  branches:
    exclude:
      - main # we don't need to build in isolation on merges to main
  paths:
    include:
      - response-items/src/discrete-scale/*

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - template: templates/yarn-cached.yml
  - template: templates/js-package.build.yml
    parameters:
      packageName: "@decsys/rating-scales"
  - template: templates/js-package.build.yml
    parameters:
      packageName: response-items
      buildScript: build:discrete-scale
