trigger:
  batch: true
  branches:
    exclude:
      - master # we don't need to build in isolation on merges to master
  paths:
    include:
      - response-items/discrete-scale/*

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/yarn-cached.yml
  - template: templates/js-package.build.yml
    parameters:
      packageName: "@decsys/rating-scales"
  - template: templates/js-package.build.yml
    parameters:
      packageName: "@decsys/discrete-scale-response"
