trigger:
  batch: true
  paths:
    include:
      - response-items/freetext/*

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/yarn-cached.yml
  - template: templates/js-package.build.yml
    parameters:
      packageName: "@decsys/freetext-response"
