trigger:
  batch: true
  paths:
    include:
      - packages/rating-scales/*

pr: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/js-package.build.yml
    parameters:
      packageName: "@decsys/rating-scales"
