trigger:
  batch: true
  paths:
    include:
      - packages/rating-scales/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  packageName: '@decsys/rating-scales'
  yarnCache: '.yarn/cache'

steps:
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | "$(packageName)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)" | "$(packageName)"
      path: $(yarnCache)
    displayName: Cache Yarn packages

  - bash: yarn workspaces focus $(packageName)
    displayName: yarn --focus
    
  - bash: yarn workspace $(packageName) build
    displayName: yarn build