trigger:
  batch: true
  paths:
    include:
      - packages/rating-scales/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  packageName: '@decsys/rating-scales'

steps:
  - bash: yarn workspaces focus $(packageName)
    displayName: yarn --focus
  - bash: yarn workspace $(packageName) build
    displayName: yarn build