root: true
env:
  browser: true
  es2023: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  # TODO: - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - "@typescript-eslint"
