packageExtensions:
  "@chakra-ui/alert-dialog@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/collapse@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/core@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/css-reset@*":
    dependencies:
      "@emotion/core": "*"
  "@chakra-ui/drawer@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/hooks@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/portal@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/styled-base": "*"
  "@chakra-ui/toast@*":
    dependencies:
      react-dom: "*"
  "@chakra-ui/utils@*":
    dependencies:
      react: "*"
  "@docusaurus/core@*":
    dependencies:
      "@docusaurus/preset-classic": next
      lodash.flatmap: "*"
  "@docusaurus/plugin-content-docs@*":
    dependencies:
      chalk: "*"
      lodash: "*"
  "@reach/alert@*":
    dependencies:
      react-dom: "*"
  react-async@*:
    dependencies:
      prop-types: "*"
  react-loadable-ssr-addon@*:
    dependencies:
      "@babel/runtime": "*"
  react-transition-group@*:
    dependencies:
      react-dom: "*"
  victory-area@*:
    peerDependencies:
      react: "*"
  victory-axis@*:
    peerDependencies:
      react: "*"
  victory-bar@*:
    peerDependencies:
      react: "*"
  victory-box-plot@*:
    peerDependencies:
      react: "*"
  victory-brush-container@*:
    peerDependencies:
      react: "*"
  victory-brush-line@*:
    peerDependencies:
      react: "*"
  victory-candlestick@*:
    peerDependencies:
      react: "*"
  victory-chart@*:
    peerDependencies:
      react: "*"
  victory-core@*:
    peerDependencies:
      react: "*"
  victory-create-container@*:
    peerDependencies:
      react: "*"
  victory-cursor-container@*:
    peerDependencies:
      react: "*"
  victory-errorbar@*:
    peerDependencies:
      react: "*"
  victory-group@*:
    peerDependencies:
      react: "*"
  victory-histogram@*:
    peerDependencies:
      react: "*"
  victory-legend@*:
    peerDependencies:
      react: "*"
  victory-line@*:
    peerDependencies:
      react: "*"
  victory-pie@*:
    peerDependencies:
      react: "*"
  victory-polar-axis@*:
    peerDependencies:
      react: "*"
  victory-scatter@*:
    peerDependencies:
      react: "*"
  victory-selection-container@*:
    peerDependencies:
      react: "*"
  victory-shared-events@*:
    peerDependencies:
      react: "*"
  victory-stack@*:
    peerDependencies:
      react: "*"
  victory-tooltip@*:
    peerDependencies:
      react: "*"
  victory-voronoi-container@*:
    peerDependencies:
      react: "*"
  victory-voronoi@*:
    peerDependencies:
      react: "*"
  victory-zoom-container@*:
    peerDependencies:
      react: "*"
  victory@*:
    peerDependencies:
      react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-berry.js
