yarnPath: ".yarn/releases/yarn-berry.js"

packageExtensions:
  # victory >.<
  "victory-area@*":
    peerDependencies:
      "react": "*"
  "victory-axis@*":
    peerDependencies:
      "react": "*"
  "victory-bar@*":
    peerDependencies:
      "react": "*"
  "victory-box-plot@*":
    peerDependencies:
      "react": "*"
  "victory-brush-container@*":
    peerDependencies:
      "react": "*"
  "victory-brush-line@*":
    peerDependencies:
      "react": "*"
  "victory-candlestick@*":
    peerDependencies:
      "react": "*"
  "victory-chart@*":
    peerDependencies:
      "react": "*"
  "victory-core@*":
    peerDependencies:
      "react": "*"
  "victory-create-container@*":
    peerDependencies:
      "react": "*"
  "victory-cursor-container@*":
    peerDependencies:
      "react": "*"
  "victory-errorbar@*":
    peerDependencies:
      "react": "*"
  "victory-group@*":
    peerDependencies:
      "react": "*"
  "victory-histogram@*":
    peerDependencies:
      "react": "*"
  "victory-legend@*":
    peerDependencies:
      "react": "*"
  "victory-line@*":
    peerDependencies:
      "react": "*"
  "victory-pie@*":
    peerDependencies:
      "react": "*"
  "victory-polar-axis@*":
    peerDependencies:
      "react": "*"
  "victory-scatter@*":
    peerDependencies:
      "react": "*"
  "victory-selection-container@*":
    peerDependencies:
      "react": "*"
  "victory-shared-events@*":
    peerDependencies:
      "react": "*"
  "victory-stack@*":
    peerDependencies:
      "react": "*"
  "victory-tooltip@*":
    peerDependencies:
      "react": "*"
  "victory-voronoi-container@*":
    peerDependencies:
      "react": "*"
  "victory-voronoi@*":
    peerDependencies:
      "react": "*"
  "victory-zoom-container@*":
    peerDependencies:
      "react": "*"
  "victory@*":
    peerDependencies:
      "react": "*"

  # peer dependencies, which we do have, so not sure why...
  "react-transition-group@*":
    dependencies:
      "react-dom": "*"
  "@reach/alert@*":
    dependencies:
      "react-dom": "*"

  # Chakra
  "@chakra-ui/portal@*":
    dependencies:
      "react-dom": "*"
  "@chakra-ui/toast@*":
    dependencies:
      "react-dom": "*"
  "@chakra-ui/utils@*":
    dependencies:
      "react": "*"
  "@chakra-ui/collapse@*":
    dependencies:
      "react-dom": "*"
  "@chakra-ui/hooks@*":
    dependencies:
      "react-dom": "*"
  "@chakra-ui/css-reset@*":
    dependencies:
      "@emotion/core": "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/styled-base": "*"
  "@chakra-ui/core@*":
    dependencies:
      "react-dom": "*"
  "@chakra-ui/drawer@*":
    dependencies:
      "react-dom": "*"
  "@chakra-ui/alert-dialog@*":
    dependencies:
      "react-dom": "*"

  # docusaurus bits
  "react-loadable-ssr-addon@*":
    dependencies:
      "@babel/runtime": "*"
  "@docusaurus/core@*":
    dependencies:
      "lodash.flatmap": "*"
      "@docusaurus/preset-classic": "next"
  "@docusaurus/plugin-content-docs@*":
    dependencies:
      "chalk": "*"
      "lodash": "*"
