# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: Build
  jobs:

  - job: dotnet_build
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
      buildConfiguration: 'Release'

    steps:
    - script: dotnet build -c $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

  - job: client_build
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: './Decsys/ClientApp'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: './Decsys/ClientApp'
        customCommand: 'run build'