# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: ClientApp
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: npm ci
    displayName: 'npm ci'
  - script: npm run build
    displayName: 'Webpack Production Build'
  # TODO test
  # TODO publish
- job: DotnetBuild
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk'
      version: '2.2.201' # replace this value with the version that you need for your project
  - script: dotnet build -c $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
    # TODO test
    # TODO artefact for parallelism
# - job: dotnet publish
#   dependsOn:
#   - ClientApp
#   - dotnet build
#   steps:
#   # fetch artifacts?
#   - script: dotnet publish -c $(buildConfiguration) --no-build
#     displayName: 'dotnet publish'
#   # TODO artifact
# - job: Win-x64 publish
#   dependsOn:
#   - ClientApp
#   - dotnet build
#   steps:
#   # todo fetch client artifact
#   - script: dotnet publish -c $(buildConfiguration) -r win-x64
#     displayName: 'dotnet publish win-x64'
#   # TODO artifact
