# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: Build
  jobs:

  - job: dotnet_build
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
      buildConfiguration: 'Release'

    steps:
    - script: dotnet build -c $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

  - job: client_build
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
    - task: Npm@1
      displayName: 'npm ci'
      inputs:
        command: 'custom'
        workingDir: './Decsys/ClientApp'
        customCommand: 'ci'
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        command: 'custom'
        workingDir: './Decsys/ClientApp'
        customCommand: 'run build'
  
  - job: load_project_metadata
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
    - task: LoadJsonVariables@1
      displayName: 'Load package.json data'
      inputs:
        JsonSource: './Decsys/ClientApp/package.json'
        VariablePrefix: 'pkg'
    - task: LoadXmlVariables@1
      displayName: 'Load .csproj data'
      inputs:
        XmlSource: './Decsys/Decsys.csproj'
        VariablePrefix: 'csproj'
        
  - job: version_file
    dependsOn: load_project_metadata
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
    - task: file-creator@5
      inputs:
        fileoverwrite: true
        skipempty: true
        filepath: './Decsys/version.txt'
        filecontent: 'Build=$(Build.BuildNumber)
Client App=$(pkg_version)'

  - job: fetch_components
    pool:
      vmImage: 'Ubuntu-16.04'
    
    steps:
    - task: DownloadGitHubRelease@0
      inputs:
        connection: 'decsys-pipelines'
        userRepository: 'ellipse-component'
        defaultVersionType: 'latest'
        downloadPath: './Decsys/components/'