version: "3.8"
services:
  database:
    image: "mongo:latest"
    container_name: "mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=mongoDB
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
