name: decsys-dev
services:
  database:
    image: "mongo:latest"
    container_name: "mongo-container"
    environment:
      - MONGO_INITDB_DATABASE=mongoDB
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
