trigger:
  - master
stages:
  - stage: Release
    condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
    jobs:
      - deployment: npm
        environment: github
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: Npm@1
                  inputs:
                    command: publish
                    publishEndpoint: npmjs
