//Taken from https://gist.github.com/ijmacdowell/8325491#file-adjectives-js
export default [
  "aback",
  "abaft",
  "abandoned",
  "abashed",
  "watery",
  "wistful",
  "witty",
  "woebegone",
  "womanly",
  "wonderful",
  "wooden",
  "woozy",
  "yummy",
  "zany",
  "zealous",
  "zesty",
  "zippy",
  "zonked",
];
