name: Build JS
description: Runs the build script for a JS package

inputs:
  package:
    required: true
    type: string
  script:
    default: build
    type: string

runs:
  using: composite
  steps:
    - run: >-
        pnpm
        --filter ${{ inputs.package }}
        ${{ inputs.script }}
