language: node_js
node_js:
  - "node"
script:
  - npm run build:prod
  - npm run docs
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
      branch: master
