name: Build Backend API

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - app/Decsys/**
      - .github/workflows/build.backend-api.yml

env:
  # Configure these
  CI_build-config: release
  CI_dotnet-version: 6.0.x
  CI_project: ./app/Decsys/Decsys.csproj

  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.CI_dotnet-version }}
      - name: dotnet build
        run: >-
          dotnet build
          ${{ env.CI_project }}
          -c ${{ env.CI_build-config }}
