name: Build Docs Website

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/build.docs.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/template.pnpm-install
        with:
          filter: docs

      - uses: ./.github/actions/template.build.js
        with:
          package: docs
