name: Build Multi Visual Analog Scale

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - response-items/src/multi-visual-analog-scale/**
      - response-items/.rollup/multi-visual-analog-scale.js
      - response-items/package.json
      - config/response-item*.js
      - .github/workflows/build.response.multi-visual-analog-scale.yml

env:
  item-name: multi-visual-analog-scale
  package: response-items

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/template.pnpm-install
        with:
          package: ${{ env.package }}

      - uses: ./.github/actions/template.build.js
        with:
          package: ${{ env.package }}
          script: build:${{ env.item-name }}
