name: Build Web Frontend

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - app/client-app/**
      - .github/workflows/build.web-frontend.yml

env:
  package: client-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/template.pnpm-install
        with:
          package: ${{ env.package }}

      # Vitest
      # TODO: move to composite action?

      # - run: >-
      #     pnpm
      #     --filter ${{ env.package }}
      #     test:ci

      # - name: Test Report
      #   uses: phoenix-actions/test-reporting@v8
      #   id: test-report # Set ID reference for step
      #   if: success() || failure() # run this step even if previous step failed
      #   with:
      #     name: Vitest Tests # Name of the check run which will be created
      #     path: app/client-app/vitest-results.xml # Path to test results
      #     reporter: jest-junit # Format of test results

      - uses: ./.github/actions/template.build.js
        with:
          package: ${{ env.package }}
