name: Build Choose One

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - response-items/src/choose-one/**
      - response-items/.rollup/choose-one.js
      - response-items/package.json
      - config/response-item*.js
      - .github/workflows/build.response.choose-one.yml

env:
  item-name: choose-one
  package: response-items

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/template.pnpm-install
        with:
          package: ${{ env.package }}

      - uses: ./.github/actions/template.build.js
        with:
          package: ${{ env.CI_package }}
          script: build:${{ env.item-name }}
